### ISSUE TITLE
Multiple `altvsntags` are treated as a single one

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/mrg-import#3]
When building the tev2-specifiations website, the MRG importer produces [this log](https://github.com/tno-terminology-design/tev2-specifications/actions/runs/6467755119/job/17558447566), that contains:

~~~ text
10:03:53:377	INFO	  - Requesting 'https://raw.githubusercontent.com/essif-lab/framework/master/docs/glossaries/mrg.essiflab.terms.yaml'
10:03:53:761	INFO	    - Storing MRG file 'mrg.essif-lab.terms.yaml' in 'docs/glossaries'
10:03:53:762	INFO	    - Creating symbolic link for default version 'mrg.essif-lab.yaml' > 'mrg.essif-lab.terms.yaml'
10:03:53:763	INFO	    - Creating symbolic link 'mrg.essif-lab.curated-terms, owned-terms.yaml' > 'mrg.essif-lab.terms.yaml'
~~~

The last line in the text file shows that the two `altvsntags`, i.e., `curated-terms` and `owned-terms`, are considered as a single tag rather than two, leading to the creation of a single symbolic link rather than two distinct links.

**Comment by Ca5e** [comment]
I believe this issue has been addressed in [this](https://github.com/essif-lab/framework/commit/26f591509c8152ff915769ec31404486612fc4db) SAF change of essif-lab/framework, changing the string value of `altvsntags` into an actual list. Unless we want to split a possible string input for `altvsntags` on a seperator (a comma in this case) before using it, I believe this to be the correct behaviour.
